GET /api/users
Host: localhost:8100
Accept: application/json

###

POST /api/register
Host: localhost:8100
Accept: application/json
Content-Type: application/json

{
  "email": "vinod@vinod.co", 
  "name": "Vinod Kumar",
  "password": "topsecret" ,
   "address": {
     "houseno": 301, 
     "street": "Elegant Elite, 1st cross, 1st main, ISRO layout", 
     "city": "Bangalore", 
     "state": "Karnataka",  
     "zip": 560078
  }   
}

###
GET /api/users/1
Host: localhost:8100
Accept: application/json

###
GET /api/users/123
Host: localhost:8100
Accept: application/json
###

PUT /api/users/1
Host: localhost:8100
Accept: application/json
Content-Type: application/json

{
  "email": "vinod@vinod.co", 
  "name": "Vinod Kumar Kayartaya",
  "password": "topsecret" ,
   "address": {
     "houseno": 301, 
     "street": "Elegant Elite, 1st cross, 1st main, ISRO layout", 
     "city": "Bangalore", 
     "state": "Karnataka",  
     "zip": 560078
  }   
}
###

PUT /api/users/122
Host: localhost:8100
Accept: application/json
Content-Type: application/json

{
  "email": "vinod@vinod.co", 
  "name": "Vinod Kumar Kayartaya",
  "password": "topsecret" ,
   "address": {
     "houseno": 301, 
     "street": "Elegant Elite, 1st cross, 1st main, ISRO layout", 
     "city": "Bangalore", 
     "state": "Karnataka",  
     "zip": 560078
  }   
}

###

DELETE /api/users/122
Host: localhost:8100
Accept: application/json
Content-Type: application/json

###

DELETE /api/users/1
Host: localhost:8100
Accept: application/json
Content-Type: application/json


###

POST /api/authenticate
Host: localhost:8100
Content-Type: application/json

{
  "email": "vinod@vinod.co",
  "password": "topsecret"
}